### ISSUE TITLE
Integrate pull request mechanism for editing nodes ... 

### ISSUE THREAD

**Issue by GuillaumeAV** [jmvanel/semantic_forms#100]
Each one manage his nodes, everyone can edit every nodes,  but each one can accept or not contributions about his nodes ... 

Like a pull request ... 

Mid-term perspective I guess ..

**Comment by jmvanel** [comment]
The first thing to do is to indicate in the form who did each triple.
Currently there is no notion of ownership for one node.

Every user has his named graph, where all his contributions are contained.
And these contributions can be about any subject.

**Comment by jmvanel** [comment]
Now things are much clearer because each group of triple has an author shown in the /display page .
And soon, each triple will have an author shown in the /display page .

Currently , the goal of SF is to share data, and display together everyone's contributions, with traceability.

Making a collaborative editor for object triples of not a goal.
However, via multiple triples contributed on datatype properties, it is possible to comment what others have done.
