### ISSUE TITLE
Strange result with the Fabio ontology

### ISSUE THREAD

**Issue by moissinac** [jmvanel/semantic_forms#107]
Trying to use 
http://purl.org/spar/fabio/
from reference in LOV for bibliographic entities
I'm referencing the work class
http://purl.org/spar/fabio/Work
I get only three properties:
label
comment 
type
which is not representative of this type of entity in Fabio

**Comment by jmvanel** [comment]
Having just these three properties:
label , comment , type
is the sure sign that for some reason, the class and its properties have not been loaded in SF .

SF reuses Jena 3.1.0 generic URL loader, but in this particular case, it was not able to load
http://purl.org/spar/fabio/Work
The reason is probably that there are 2 "See Other" HTTP steps.

Note that wget does better than Jena loader:

```
 wget --header='Accept: text/turtle' http://purl.org/spar/fabio/Work
--2016-11-06 17:08:51--  http://purl.org/spar/fabio/Work
Résolution de purl.org (purl.org)… 207.241.224.2
Connexion à purl.org (purl.org)|207.241.224.2|:80… connecté.
requête HTTP transmise, en attente de la réponse… 302 FOUND
Emplacement : http://sempublishing.sourceforge.net/fabio/Work [suivant]
--2016-11-06 17:08:53--  http://sempublishing.sourceforge.net/fabio/Work
Résolution de sempublishing.sourceforge.net (sempublishing.sourceforge.net)… 216.34.181.96
Connexion à sempublishing.sourceforge.net (sempublishing.sourceforge.net)|216.34.181.96|:80… connecté.
requête HTTP transmise, en attente de la réponse… 303 See Other
Emplacement : http://www.sparontologies.net/ontologies/fabio/source [suivant]
--2016-11-06 17:08:53--  http://www.sparontologies.net/ontologies/fabio/source
Résolution de www.sparontologies.net (www.sparontologies.net)… 212.47.249.17
Connexion à www.sparontologies.net (www.sparontologies.net)|212.47.249.17|:80… connecté.
requête HTTP transmise, en attente de la réponse… 303 See Other
Emplacement : http://www.sparontologies.net/ontologies/fabio/source.ttl [suivant]
--2016-11-06 17:08:53--  http://www.sparontologies.net/ontologies/fabio/source.ttl
Réutilisation de la connexion existante à www.sparontologies.net:80.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : non indiqué
Enregistre : «Work»

Work                                              [ <=>                                                                                              ] 130,99K  --.-KB/s    in 0,07s   

2016-11-06 17:08:58 (1,81 MB/s) - «Work» enregistré [134138]
```

The solution in this case is take the explicit OWL link:
https://svn.code.sf.net/p/sempublishing/code/FaBiO/2016-04-19-fabio-1_9_2.owl
paste it in "Display" field; then you see the good statistics:
522 subjects, 2070 triples, ... 1053 objects ...

Then we get this:
http://163.172.179.125:9111/create?uri=http%3A%2F%2Fpurl.org%2Fspar%2Ffabio%2FWork&uri=http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FPerson

with 2 more properties:

- has portrayal
- has manifestation 

I don't know this ontology; please tell if this is correct.

And be assured that I'll report that to Jena team :) .

**Comment by moissinac** [comment]
Thank's
It works
