### ISSUE TITLE
Migration to BigData(R)

### ISSUE THREAD

**Issue by balessan** [jmvanel/semantic_forms#6]
Depend on "Remove Jena dependencies in code" #21

**Comment by jmvanel** [comment]
Take inspiration of what was bone in recent refactoring in cityData:
pixelhumain/cityData@ca9152f

**Comment by jmvanel** [comment]
The Open Source future of BlazeGraph is hazy , see : 
https://github.com/blazegraph/database/issues/53
 _The primary Blazegraph development is done closed-source with open source releases,_

So that's much like Android :( .

Anyway, the current usage of Jena TDB is satifying.
Anyway, the port should be doable thanks to Banana RDF compatibility layer.
